import { InventoryItem, LogEntry } from './types';

export const initialInventory: InventoryItem[] = [
  // Shibuya Office (Main Commercial Hub)
  {
    id: 'shib-01',
    name: 'Eco-Cleaner All-Purpose Spray',
    category: 'Sprays & Chemicals',
    location: 'shibuya',
    startingStock: 15,
    deliveries: 4,
    used: 7,
    currentStock: 12,
    minThreshold: 5,
    unit: 'bottles',
    lastUpdated: '2026-07-01T10:00:00Z',
  },
  {
    id: 'shib-02',
    name: 'Microfiber Cloths (Blue)',
    category: 'Cloth & Pads',
    location: 'shibuya',
    startingStock: 30,
    deliveries: 5,
    used: 10,
    currentStock: 25,
    minThreshold: 10,
    unit: 'packs',
    lastUpdated: '2026-07-02T11:30:00Z',
  },
  {
    id: 'shib-03',
    name: 'Heavy Duty Trash Bags (45L)',
    category: 'Trash Bags',
    location: 'shibuya',
    startingStock: 10,
    deliveries: 2,
    used: 4,
    currentStock: 8,
    minThreshold: 3,
    unit: 'rolls',
    lastUpdated: '2026-07-03T15:20:00Z',
  },
  {
    id: 'shib-04',
    name: 'Premium Bleach Concentrate',
    category: 'Sprays & Chemicals',
    location: 'shibuya',
    startingStock: 6,
    deliveries: 1,
    used: 2,
    currentStock: 5,
    minThreshold: 2,
    unit: 'bottles',
    lastUpdated: '2026-06-29T09:15:00Z',
  },
  {
    id: 'shib-05',
    name: 'Eco Dishwashing Liquid',
    category: 'Sprays & Chemicals',
    location: 'shibuya',
    startingStock: 12,
    deliveries: 2,
    used: 4,
    currentStock: 10,
    minThreshold: 4,
    unit: 'bottles',
    lastUpdated: '2026-07-05T08:45:00Z',
  },
  {
    id: 'shib-06',
    name: 'Soft Toilet Paper Packs',
    category: 'Paper Products',
    location: 'shibuya',
    startingStock: 20,
    deliveries: 5,
    used: 10,
    currentStock: 15,
    minThreshold: 6,
    unit: 'packs',
    lastUpdated: '2026-07-06T14:10:00Z',
  },
  {
    id: 'shib-07',
    name: 'Toilet Cleaner Gel',
    category: 'Sprays & Chemicals',
    location: 'shibuya',
    startingStock: 8,
    deliveries: 0,
    used: 4,
    currentStock: 4, // ALERT: Below Threshold of 5
    minThreshold: 5,
    unit: 'bottles',
    lastUpdated: '2026-07-04T12:00:00Z',
  },
  {
    id: 'shib-08',
    name: 'Floor Mopping Concentrate',
    category: 'Sprays & Chemicals',
    location: 'shibuya',
    startingStock: 5,
    deliveries: 0,
    used: 3,
    currentStock: 2, // ALERT: Below Threshold of 3
    minThreshold: 3,
    unit: 'bottles',
    lastUpdated: '2026-07-01T16:00:00Z',
  },

  // Jeffrey Skytree Hub (Luxury Guest/Airbnb Hub)
  {
    id: 'sky-01',
    name: 'Custom Luxury Linens Set',
    category: 'Guest Amenities',
    location: 'skytree',
    startingStock: 35,
    deliveries: 5,
    used: 8,
    currentStock: 32,
    minThreshold: 15,
    unit: 'sets',
    lastUpdated: '2026-07-02T13:45:00Z',
  },
  {
    id: 'sky-02',
    name: 'Organic Amenity Shampoo',
    category: 'Guest Amenities',
    location: 'skytree',
    startingStock: 150,
    deliveries: 20,
    used: 50,
    currentStock: 120,
    minThreshold: 50,
    unit: 'bottles',
    lastUpdated: '2026-07-03T10:30:00Z',
  },
  {
    id: 'sky-03',
    name: 'Organic Amenity Conditioner',
    category: 'Guest Amenities',
    location: 'skytree',
    startingStock: 80,
    deliveries: 5,
    used: 50,
    currentStock: 35, // ALERT: Below Threshold of 50
    minThreshold: 50,
    unit: 'bottles',
    lastUpdated: '2026-07-04T11:20:00Z',
  },
  {
    id: 'sky-04',
    name: 'Custom Scented Reed Diffusers',
    category: 'Guest Amenities',
    location: 'skytree',
    startingStock: 15,
    deliveries: 2,
    used: 5,
    currentStock: 12,
    minThreshold: 5,
    unit: 'units',
    lastUpdated: '2026-06-30T15:00:00Z',
  },
  {
    id: 'sky-05',
    name: 'Premium Microfiber Mop Pads',
    category: 'Cloth & Pads',
    location: 'skytree',
    startingStock: 12,
    deliveries: 0,
    used: 6,
    currentStock: 6, // ALERT: Below Threshold of 8
    minThreshold: 8,
    unit: 'packs',
    lastUpdated: '2026-07-01T09:00:00Z',
  },
  {
    id: 'sky-06',
    name: 'Airbnb Welcome Cards',
    category: 'Guest Amenities',
    location: 'skytree',
    startingStock: 25,
    deliveries: 5,
    used: 15,
    currentStock: 15, // ALERT: Below Threshold of 20
    minThreshold: 20,
    unit: 'cards',
    lastUpdated: '2026-07-05T17:30:00Z',
  },
  {
    id: 'sky-07',
    name: 'Eco-Luxury Hand Soap',
    category: 'Guest Amenities',
    location: 'skytree',
    startingStock: 20,
    deliveries: 4,
    used: 6,
    currentStock: 18,
    minThreshold: 10,
    unit: 'bottles',
    lastUpdated: '2026-07-06T11:00:00Z',
  },
];

export const initialLogs: LogEntry[] = [
  {
    id: 'log-01',
    timestamp: '2026-07-01T10:00:00Z',
    type: 'delivery',
    location: 'shibuya',
    itemName: 'Eco-Cleaner All-Purpose Spray',
    quantity: 4,
    staffName: 'Manager Kenji',
    notes: 'Monthly bulk cleaning chemical dispatch',
    source: 'manual',
  },
  {
    id: 'log-02',
    timestamp: '2026-07-02T14:30:00Z',
    type: 'use',
    location: 'shibuya',
    itemName: 'Eco-Cleaner All-Purpose Spray',
    quantity: 3,
    staffName: 'Cleaning Staff Yuto',
    notes: 'Standard Shibuya evening cleaning cycle',
    source: 'google_form',
  },
  {
    id: 'log-03',
    timestamp: '2026-07-03T10:30:00Z',
    type: 'delivery',
    location: 'skytree',
    itemName: 'Organic Amenity Shampoo',
    quantity: 20,
    staffName: 'Manager Kenji',
    notes: 'Airbnb stock restock',
    source: 'manual',
  },
  {
    id: 'log-04',
    timestamp: '2026-07-04T11:20:00Z',
    type: 'use',
    location: 'skytree',
    itemName: 'Organic Amenity Conditioner',
    quantity: 12,
    staffName: 'Cleaning Staff Haruka',
    notes: 'Skytree luxury room turn-down service',
    source: 'google_form',
  },
  {
    id: 'log-05',
    timestamp: '2026-07-05T17:30:00Z',
    type: 'use',
    location: 'skytree',
    itemName: 'Airbnb Welcome Cards',
    quantity: 5,
    staffName: 'Cleaning Staff Haruka',
    notes: 'Placed in rooms for upcoming guests',
    source: 'google_form',
  },
  {
    id: 'log-06',
    timestamp: '2026-07-06T14:10:00Z',
    type: 'use',
    location: 'shibuya',
    itemName: 'Soft Toilet Paper Packs',
    quantity: 4,
    staffName: 'Cleaning Staff Yuto',
    notes: 'Restocked all 3 floor restrooms',
    source: 'google_form',
  },
];
